README.md

Disable interactive and tty for docker exec call

---

Dockerfile
src/silverkey-client.go

add fuzzy search

---

src/silverkey-client.go

Change-Id: I9a439b323594e00c82e0ed63220dd4cb618f800e

First UI implementation

---

src/mainwindow.cpp

Close ui when user click on item.

---

src/main.cpp
src/mainwindow.cpp

Issue20 autofocus

---

src/main.cpp
src/silverkey-qt.pro

Change-Id: I52ebdf52b4afa4d49d1b2a97d08b3e82e2f2de14

Added OSX config and fork

---

src/main.cpp
src/mainwindow.cpp
src/mainwindow.h

Change-Id: I55e7e77c5b98b48a5db759b7f930ac6dd9452dc0

Raw implementation of pipe between processes

---

src/main.cpp

Change-Id: I866267856ecf7a197250d0bca1345c4d39f598ab

Increased keyboard speed

---

src/mainwindow.cpp

Change-Id: If9166adcccbe80c4316f713dbb9178a6fd04a139

Proper key search and app close handler

---

src/fuzzycompleter.cpp
src/fuzzycompleter.h
src/main.cpp
src/mainwindow.cpp
src/mainwindow.h
src/silverkey-qt.pro

* Moved custom classes to separate files
* Implemented Sorting proxy from completer
* Fixed Levinstein
Change-Id: I49376f5183ca1d072cf0f31951e9368bb2399563

Added Fuzzy search for completer

---

src/main.cpp
src/mainwindow.cpp
src/mainwindow.h

Change-Id: I555c240c63755066350e2ff0f17081df31b05569

Write data to etcd via CLI args

---

src/mainwindow.cpp

Change-Id: Id66f4ae429d2da4a550614960fd468d64d6f5f11

Added popup settings from QCompleter

---

src/mainwindow.cpp

Use popup window as mainwindow

---

src/fuzzycompleter.cpp
src/fuzzycompleter.h
src/mainwindow.cpp
src/mainwindow.h

Change-Id: Ia1ee2b1ce1729b69576b0f4b3a84c7ed8f9c19d8

Lock input while data is loading

---

src/mainwindow.cpp
src/mainwindow.h

Change-Id: I3ddc7ac65ee16d42222db03f7e397a58dedab22a

Added app close on Esc key

---

src/fuzzycompleter.cpp
src/fuzzycompleter.h
src/mainwindow.cpp

* For new search first match is highlighted
* Use highlighted item as key for data to paste
Change-Id: I72755d0c684b56e9a012826255e0b78877202be1

Selector for data key instead of LineEdit

---

.gitignore

Change-Id: I8f5f575c01c95688989716fa0562535f39c8e3cc

git should ignore artifacts dir

---

ci-xfce.Dockerfile
irssi_config
test-scenario.sh
twitch.Dockerfile
twitch_ci_broadcast.sh

https://www.twitch.tv/silverkey_project/

Twitch ci screencast

---

Dockerfile
Jenkinsfile
docker/qt-trusty/Dockerfile
docker/qt-trusty/extract-qt-installer.sh
wm-xfce-trusty.Dockerfile

issue174 old glibc

---

tests/osx/SKBase.applescript
tests/osx/run_tests.sh
tests/osx/test_base_paste_ops.applescript

Change-Id: I787b7ffb0ce5625093e3f92d990e6e2d2b824ff0

Basic OSX tests implementation
